* Unit Study Guides

** Unit 1 - What is the proper role of government?

*** Introduction and Ideology :: Chapter 1 and 12.1 
Declaration of Independence
Democracy
Natural Rights
Social Contract
Popular Sovereignty
Republicanism
Limited Government
Inalienable Rights
Participatory Democracy
Pluralist Democracy
Elite Democracy
Constitutional Republic
Political Ideology
Conservatism
Liberalism
Libertarianism
+ Explain how models of representative democracy are visible in major institutions, policies, events, or debates in the U.S.
+ Explain how the ideologies of the two major parties shape policy debates.
+ Explain how U.S. political culture (e.g., values, attitudes, and beliefs) influences the formation, goals, and implementation of public policy over time.


*** Constitution :: Chapter 2  
Republic
Articles of Confederation
Unicameral
Shay's Rebellion
Great (Connecticut) Compromise
Bicameral
Three-Fifths Compromise
Slave trade compromise
Separation of Powers
Checks and Balances
Federalism
Amendment
Impeachment
Federalists
Legislative Branch
Anti-Federalists
Expressed/Enumerated Powers
Federalist Papers
Necessary and Proper/Elastic Clause
*Federalist 10*
*Federalist 51*
Implied Powers
*Brutus 1*
Executive Branch
Electoral College
Judicial Branch
Supremacy Clause
+ Explain how democratic ideals are reflected in the Declaration of Independence and the U.S. Constitution 
+ Explain how Federalist and Anti- Federalist views on central government and democracy are reflected in U.S. foundational documents.
+ Explain the relationship between key provisions of the Articles of Confederation and the debate over granting the federal government greater power formerly reserved to the states.
+ Explain the ongoing impact of political negotiation and compromise at the Constitutional Convention on the development of the constitutional system.
+ Explain the constitutional principles of separation of powers and checks and balances.
+ Explain the implications of separation of powers and checks and balances for the U.S. political system.
+ Explain the amendment process 


*** Federalism :: Chapter 3
Incentives
Commerce Clause
14th Amendment
10th Amendment
Dual Federalism
Unfunded Mandates
Delegated Powers
Cooperative Federalism
Block Grants
Reserved Powers
Grants-In-Aid
Revenue Sharing
Concurrent Powers
MuCulloch v Aaryiand
Fiscal Federalism
Aid programs
Categorical Grants
United States v Lopez
+ Explain how societal needs affect the constitutional allocation of power between the national and state governments.
+ Explain how the appropriate balance of power between national and state governments has been interpreted differently over time. 
+ Explain how the distribution of powers among three federal branches and between national and state governments impacts policy making. 


** Unit 2 - Now does the judicial branch balance liberty and order?

*** Judiciary :: Chapter 6
Original Jurisdiction
fvfarbuty v Madison
Concurring Opinion
Appellate Jurisdiction
Precedents
Dissenting Opinion
Federalist 78
Stare Decisis
Judicial Activism
Judicial Review
Majority opinion
Judicial Restraint
+ Explain the principle of judicial review and how it checks the power of other institutions and state governments. 
+ Explain how the exercise of judicial review in conjunction with life tenure can lead to debate about the legitimacy of the Supreme Court's power 
+ Explain how other branches in the government can limit the Supreme Court's power 


*** Civil Liberties :: Chapter 8
Civil Liberties
Bill of Rights
14th Amendment
Due Process Clause
Selective Incorporation
Establishment Clause
Free Exercise Clause
Engel v Vitale
Wisconsin v Yoder
Freedom of Expression
"Clear and Present Danger"
Schenck v United States
Prior Restraint
New York Times v United States
Symbolic Speech
Tinker v Des Moines
Libel/Slander
Defamation
Obscenity
Time, manner and place regulations
2nd Amendment
McDonald v Chicago
4th Amendment 
Exclusionary Rule
5th Amendment
Miranda Rule
Public Safety Exception
6th Amendment
Gideon v Wainwright
8th Amendment
Patriot Act
USA Freedom Act
Roe v Wade 
+ Explain how the U.S. Constitution protects individual liberties and rights. 
+ Describe the rights protected in the Bill of Rights. 
+ Explain the extent to which the Supreme Court's interpretation of the First and Second Amendments reflects a commitment to individual liberty 
+ Explain how the Supreme Court has attempted to balance claims of individual freedom with laws and enforcement procedures that promote public order and safety. 
+ Explain the implications of the doctrine of selective incorporation. 
+ Explain the extent to which states are limited by the due process clause from infringing upon individual rights. 

*** Civil Rights :: Chapter 9
Civil Rights
13th Amendment
14th Amendment
Equal Protection Clause
15th Amendment
Brown v Board of Education 
Affirmative Action
"Letter from Birmingham Jail"
Civil Rights Act of 1964
Voting Rights Act of 1965
19th Amendment
National Organization for Women
Title IX of the Education Amendments Act of 1972 
+ Explain how constitutional provisions have supported and motivated social movements 
+ Explain how the government has responded to social movements. 
+ Explain how the Supreme Court has at times allowed the restriction of the civil rights of minority groups and at other times has protected those rights.